//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elections.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.TempCandidateLocals = new HashSet<TempCandidateLocal>();
            this.TempPartyCandidates = new HashSet<TempPartyCandidate>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<long> fk_ads { get; set; }
        public Nullable<long> fk_debates { get; set; }
        public Nullable<long> fk_feedback { get; set; }
        public string username { get; set; }
        public string IMG { get; set; }
    
        public virtual Ad Ad { get; set; }
        public virtual Debate Debate { get; set; }
        public virtual Feedback Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempCandidateLocal> TempCandidateLocals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempPartyCandidate> TempPartyCandidates { get; set; }
    }
}
