//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elections.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempDebate
    {
        public long id { get; set; }
        public string listname { get; set; }
        public string areaelection { get; set; }
        public string CandidateName { get; set; }
        public Nullable<int> NationalNum { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string debateDate { get; set; }
        public Nullable<System.TimeSpan> debateTime { get; set; }
    
        public virtual Debate Debate { get; set; }
    }
}
